### ISSUE TITLE
Syntex support

### ISSUE THREAD

**Issue by hansihe** [KyleMayes/easy-plugin#3]
I am the author of the [Rustler](https://github.com/hansihe/Rustler) library, which depends on easy_plugin for its compiler plugin. I am currently looking at supporting stable rust, and therefore planning to make my compiler plugin optionally use syntex.

Is it technically possible for this crate to support syntex?

**Comment by KyleMayes** [comment]
I imagine it is possible, and I have thought about adding `syntex` support. I initially decided to put it off because I wasn't sure how difficult it would be to have both a nightly plugin interface and a stable `syntex` interface. I'll look into it.

**Comment by hansihe** [comment]
I have looked at it a little bit, if I'm not mistaken syntex makes it fairly easy to support both interfaces.

Serde does it by having a cargo feature, and doing conditional imports based on that.

**Comment by hansihe** [comment]
I'll have a look, see if it seems feasible.

**Comment by KyleMayes** [comment]
It is feasible, currently adding `synthex` support to a quasiquoting crate I wrote that I recently refactored this crate to use. Once I am done with that, I will move to this crate.

**Comment by KyleMayes** [comment]
`v0.8.0` has been released with `syntex` support. Just pass the `stable` Cargo feature and you are good to go.

**Comment by hansihe** [comment]
Oh wow, that was very fast!

Thanks for the help!
